---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: godeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: gowebappcontainer
          image: mdjameelahmed/task
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: goappsvc
spec:
  type: NodePort
  selector:
    app: goapp
  ports:
    - port: 80
      targetPort: 8080
---
